name: Build

on:
  push:
    tags:
    - 'v*'
    
env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build-win32:
    runs-on: windows-latest

    steps:    
    
    - uses: hzqst/checkout@v2.3.4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Init dependencies
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git submodule update --init --recursive
      shell: cmd

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /t:BetterSpray
      
    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: Build/
          dest: BetterSpray-windows-x86.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: BetterSpray-${{ github.ref }}
          files: |
            BetterSpray-windows-x86.zip
